silex_mooc_personalization_homepage:
    path:     /
    defaults: { _controller: SilexMoocPersonalizationBundle:Home:index }
    
fileValuesModicfication:
    path: /fileValuesModification
    defaults: { _controller: SilexMoocPersonalizationBundle:FileValuesModification:index }
    
statistics:
    path: /statistics
    defaults: { _controller: SilexMoocPersonalizationBundle:Statistics:index }
    
sequence_association:
    path: /sequence_association
    defaults: { _controller: SilexMoocPersonalizationBundle:SequenceAssociation:index }
    